# Generated by Django 3.1 on 2020-08-09 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='AuctionListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_desc', models.TextField()),
                ('bid_start', models.FloatField()),
                ('image', models.CharField(blank=True, max_length=255)),
                ('date', models.DateTimeField(auto_now=True)),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_cat', to='auctions.categories')),
            ],
        ),
    ]
