# Generated by Django 3.1 on 2020-08-09 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlisting_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Categoriess',
        ),
    ]
