# Generated by Django 3.1 on 2020-08-09 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200809_1745'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoriess',
            new_name='Category',
        ),
    ]
